### ISSUE TITLE
v2.0.3 Undefined is not a function

### ISSUE THREAD

**Issue by chyld** [plus3network/gulp-less#140]
Ran into this error when using v2.0.3.
I'm on Mac OSX 10.10 running Node 0.12 64-bit.

```
Users/chyld/Code/calculator/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/Users/chyld/Code/calculator/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/Users/chyld/Code/calculator/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/chyld/Code/calculator/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/chyld/Code/calculator/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/chyld/Code/calculator/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/chyld/Code/calculator/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/chyld/Code/calculator/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/chyld/Code/calculator/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/chyld/Code/calculator/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)

```

**Comment by stevelacy** [comment]
Please add your gulp task

**Comment by baldore** [comment]
I'm having the same error. Gulp-less works when I use node 0.10.36, but doesn't run when I set node 0.12 or IO.js 1.1.0. This is my task.

```
gulp.task('less', function () {
  gulp.src('main.less')
    .pipe(less())
    .on('error', console.error.bind(console))
    .pipe(gulp.dest('css/'));
});
```

**Comment by chyld** [comment]
My gulp task

```javascript
gulp.task('less', function() {
  gulp.src(paths.lesssrc)
    .pipe(less())
    .on('error', function (err) {
      console.log(err);
    })
    .pipe(gulp.dest(paths.lessdst));
});
```

**Comment by contra** [comment]
@OhJeez looks like your PR broke for node 0.12 and io.js - any ideas?

**Comment by mattstyles** [comment]
Looks like `less.render` expects a success and error handler rather than exposing `then`, `done` and `catch`.

The fix is to move the `catch` handler into param 2 of `then` and discard the `done` handler as I think its redundant as the `then` handler dispatches the "master" callback. This certainly fixes a failing and passing compile using iojs (Ive not idea why this works in 0.10.x). I cant be sure exactly that this is anything more than a sticky-taping over something as I'm not sure the original intention of @OhJeez's PR.

Regarding 0.10.x, no idea why it still works, looks like node is simply ignoring the .catch and .done, logging the return of .then just gives another chainable .then with no `catch` or `done` methods to call. I'm going to assume this is a bug with 0.10.x and that 0.12 and 1.x behave as you would expect, but havent done a great deal of digging.

**Comment by OhJeez** [comment]
Native promise does not have .done, while then/promise has. Less includes then/promise only if no native promises are available.
https://github.com/less/less.js/blob/fb5280f16f124e5062634a22be2f3c99e650d0a4/lib/less/render.js#L12

Quick fix will be replacing `.done` with `.this`. Good fix will be always including then/promise in less/less.js . I will open an issue there.

**Comment by mattstyles** [comment]
Yeah, I just did some digging and found the same.

You mean replace `.done` with another `.then`?

**Comment by OhJeez** [comment]
@mattstyles It will work. `.done` is better, but `.then` is all we have.

**Comment by mattstyles** [comment]
@OhJeez yep, I gotcha, I was just referring to the typo in your earlier comment.

**Comment by mattstyles** [comment]
@OhJeez although, you know that final `.then` wont ever be called and is redundant in es6?

**Comment by OhJeez** [comment]
@mattstyles why? It has arguments.

**Comment by mattstyles** [comment]
@OhJeez yeah, but the `.catch` will grab any errors and throw, I'm just going to check but I thought that would end the chain. Thinking about it I guess the error propagates to the final `.then`.

**Comment by OhJeez** [comment]
@mattstyles, not if there is another error thrown inside the .catch() handler. That was one of the reasons of the #118 - there was another error thrown in handler and never caught. That `.done()` was supposed to be the last resort try to pass something to callback.

**Comment by mattstyles** [comment]
@OhJeez oh yeah, I see now, propagates straight down, makes sense I guess. Although that throws up a slightly different issue, it consumes the error so gulp thinks the less compile has been successful. I cant catch the error in the stream, unless I'm missing something?

**Comment by mattstyles** [comment]
@OhJeez Ignore my previous comment, plumber will catch the error rather using .on( 'error' ).

**Comment by contra** [comment]
Can you try the 3.0.0 branch? @jenius just sent a major PR which switches us from using less directly to using a less wrapper which handles all of this weird shit. the stuff less exports is a pain to deal with

**Comment by jumoel** [comment]
I experienced the same error, and it disappeared on 3.0.0.

**Comment by jenius** [comment]
:tada:

**Comment by CavemanNinja** [comment]
ty, 3.0.0 working for me too :+1:

**Comment by Pomax** [comment]
can 3.0.0 be pushed to npm? This keeps breaking about 20 projects I need to work on =(
