### ISSUE TITLE
Error when using sourcemaps on a less file that only contains variables

### ISSUE THREAD

**Issue by David-Hari** [plus3network/gulp-less#144]
Affects version 3.0.0

I have two files; style.less and variables.less.
variables.less just contains variable definitions and style.less imports those variables and uses them. Therefore, when transformed to CSS, the output variables.css is empty.

However, when I use sourcemaps, I get the following error:
```
C:\dev\less-test\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\decorators\unhandledRejection.js:80
                throw e;
                      ^
SyntaxError: Unexpected token u in file undefined line no. undefined
    at Object.parse (native)
    at C:\dev\less-test\node_modules\gulp-less\node_modules\accord\lib\adapters\less.js:48:32
    at C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\render.js:35:17
    at C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\parse.js:63:17
    at Object.finish [as _finish] (C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\parser\parser.js:183:28)
    at Object.ImportVisitor._onSequencerEmpty (C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\visitors\import-visitor.js:35:14)
    at ImportSequencer.tryRun (C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\visitors\import-sequencer.js:50:14)
    at Object.ImportVisitor.run (C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\visitors\import-visitor.js:29:25)
    at Object.Parser.parse (C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\parser\parser.js:189:22)
    at Object.parse (C:\dev\less-test\node_modules\gulp-less\node_modules\less\lib\less\parse.js:61:18)
```

This is my Gulp task:

    gulp.task('less', function() {
        gulp.src([ '*.less' ])
            .pipe(sourceMaps.init())
            .pipe(less())
            .pipe(sourceMaps.write('.'))
            .pipe(gulp.dest('.'));
    });

This error is avoided if I put styles in the variables.less file, such that it's output CSS file is not empty.

**Comment by David-Hari** [comment]
Could be related to https://github.com/less/less.js/issues/2430 and https://github.com/plus3network/gulp-less/issues/114.

**Comment by contra** [comment]
I think this is https://github.com/less/less.js/issues/2430
