### ISSUE TITLE
gulp-less throws own error instead of actual error in other pipe

### ISSUE THREAD

**Issue by Splurov** [plus3network/gulp-less#170]
How to reproduce:

```bash
$ git clone git@github.com:Splurov/gulp-less-errors-bug.git
$ npm install
$ gulp test
```
Output:

```
gulp-less-errors-bug $ gulp test
[22:35:49] Using gulpfile ~/Work/gulp-less-errors-bug/gulpfile.js
[22:35:49] Starting 'test'...
[22:35:49] Finished 'test' after 6.5 ms

/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
Error: no writecb in Transform class
    at afterTransform (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at tryCatchReject (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:442:13)
```

Should be something like (if we comment line 8 https://github.com/Splurov/gulp-less-errors-bug/blob/master/gulpfile.js#L8):

```
gulp-less-errors-bug $ gulp test
[22:38:23] Using gulpfile ~/Work/gulp-less-errors-bug/gulpfile.js
[22:38:23] Starting 'test'...
[22:38:23] Finished 'test' after 5.51 ms

/Users/splurov/Work/gulp-less-errors-bug/gulpfile.js:10
            throw new Error('this error never shown due to less');
                  ^
Error: this error never shown due to less
    at /Users/splurov/Work/gulp-less-errors-bug/gulpfile.js:10:19
    at Stream.modifyFile (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-tap/lib/tap.js:69:11)
    at Stream.stream.write (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp-tap/node_modules/event-stream/node_modules/through/index.js:26:11)
    at write (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/splurov/Work/gulp-less-errors-bug/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```

I think gulp-less shouldn't lose errors from other pipe.

**Comment by contra** [comment]
This happens randomly due to some weird npm bug where the stream class fails to install right - wipe node_modules and reinstall

**Comment by Splurov** [comment]
I tried about 20 times both on Mac and Ubuntu:

```
rm -rf node_modules
npm install
gulp test
```

Always got `Error: no writecb in Transform class`.

- Mac OS X, npm 2.11.3, node 0.10.39 (tried 0.12.5 with the same result).
- Ubuntu 14.04, node 0.12.4, npm 2.11.3.

**Comment by stevelacy** [comment]
Did you clear your npm cache?

**Comment by Splurov** [comment]
Yes, same result.
I even tried on clean Ubuntu without nodejs and npm — installed latest node, npm, gulp, clone my repo, `npm install && gulp test` and got the same error `no writecb...`.

**Comment by stevelacy** [comment]
I'll clone/debug the repo in a bit, I have a feeling where it's coming from.

**Comment by Splurov** [comment]
@stevelacy get anything out?

**Comment by LadyDascalie** [comment]
I am seeing the exact same issue here, `gulp-less` throws the same error, wiping / clearing cache did nothing to fix it so far

**Comment by betaorbust** [comment]
It looks like this is currently failing the build(s)
https://travis-ci.org/plus3network/gulp-less/jobs/83100799
![image](https://cloud.githubusercontent.com/assets/921683/10296165/e72a443c-6b7a-11e5-9316-12c6559dd953.png)
![image](https://cloud.githubusercontent.com/assets/921683/10296181/fb0f97e0-6b7a-11e5-9902-24ecca065994.png)

**Comment by danielbayerlein** [comment]
Same here (Windows 8.1 + node v0.12.6 + npm v2.11.2 + gulp-less v3.0.3):

```bash
C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\decorators\unhandledRejection.js:80
		throw e;
		      ^
Error: no writecb in Transform class
    at afterTransform (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:95:33)
    at TransformState.afterTransform (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at tryCatchReject (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:804:4)
    at Rejected.when (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:625:4)
    at Pending.run (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Workspace\S1510\share\node\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by AlexBen** [comment]
D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\decorators\unhandledRejection.js:80
                throw e;
                      ^
Error: no writecb in Transform class
    at afterTransform (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:95:33)
    at TransformState.afterTransform (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at tryCatchReject (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:804:4)
    at Rejected.when (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:625:4)
    at Pending.run (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (D:\Projects\gitweb\attribute-value-grid-resources\node_modules\gulp-less\node_modules\accord\node_modules\when\lib\Scheduler.js:27:9)
    at process._tickDomainCallback (node.js:381:11)

**Comment by contra** [comment]
Has anyone confirmed this is a problem on node 4?

**Comment by Splurov** [comment]
Yes:

```
~/Downloads $ node -v
v4.2.1
~/Downloads $ npm -v
2.14.7
~/Downloads $ git clone git@github.com:Splurov/gulp-less-errors-bug.git
Cloning into 'gulp-less-errors-bug'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 5
Receiving objects: 100% (7/7), done.
Checking connectivity... done.
~/Downloads $ cd gulp-less-errors-bug/
~/Downloads/gulp-less-errors-bug (master) $ npm install
npm WARN package.json gulp-less-errors-bug@1.0.0 No description
npm WARN package.json gulp-less-errors-bug@1.0.0 No repository field.
npm WARN package.json gulp-less-errors-bug@1.0.0 No README data
gulp-tap@0.1.3 node_modules/gulp-tap
└── event-stream@3.1.7 (pause-stream@0.0.11, stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, map-stream@0.1.0, split@0.2.10, through@2.3.8)

gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, fancy-log@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-less@3.0.3 node_modules/gulp-less
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── accord@0.15.2 (indx@0.2.3, convert-source-map@0.4.1, fobject@0.0.3, when@3.7.3, glob@4.5.3, resolve@1.1.6, uglify-js@2.5.0, lodash@3.10.1)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── less@2.5.3 (mime@1.3.4, graceful-fs@3.0.8, image-size@0.3.5, source-map@0.4.4, mkdirp@0.5.1, errno@0.1.4, promise@6.1.0, request@2.65.0)
~/Downloads/gulp-less-errors-bug (master) $ gulp test
[15:29:57] Using gulpfile ~/Downloads/gulp-less-errors-bug/gulpfile.js
[15:29:57] Starting 'test'...
[15:29:57] Finished 'test' after 8.48 ms
/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		^

Error: no writecb in Transform class
    at afterTransform (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at tryCatchReject (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by AlexBen** [comment]
https://travis-ci.org/plus3network/gulp-less/jobs/83100618 20 days ago :)

**Comment by MartinSahlen** [comment]
This still fails for me. Works locally, but fails on CircleCi.

**Comment by Splurov** [comment]
Same for me:

```
~/Downloads/gulp-less-errors-bug (master *) $ cat package.json 
{
  "name": "gulp-less-errors-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-less": "plus3network/gulp-less#be18b01e7087db7336a35bf2924db3a0e84984fa",
    "gulp-tap": "^0.1.3"
  }
}
~/Downloads/gulp-less-errors-bug (master *) $ npm -v
2.14.7
~/Downloads/gulp-less-errors-bug (master *) $ node -v
v4.2.1
~/Downloads/gulp-less-errors-bug (master *) $ gulp test
[09:46:37] Using gulpfile ~/Downloads/gulp-less-errors-bug/gulpfile.js
[09:46:37] Starting 'test'...
[09:46:37] Finished 'test' after 9.35 ms
Potentially unhandled rejection [2] Error: no writecb in Transform class
    at afterTransform (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:33)
    at TransformState.afterTransform (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at /Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/index.js:58:14
    at tryCatchReject (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/mk/Downloads/gulp-less-errors-bug/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:417:9)

```

**Comment by MartinSahlen** [comment]
This is an error, from what i investigated, in node 0.10.x. Try 0.12.x, 4
or 5. Any of those worked for me. Should be better at aligning my build and
dev environments, but that is another discussion. This issue need not be
opened again as far as I am concerned.

**Comment by Splurov** [comment]
I used 4.2.1.

**Comment by contra** [comment]
@MartinSahlen Try clearing the package cache on circle-ci, it might be running the previous version

**Comment by MartinSahlen** [comment]
Yes, that was exactly what I did. So I can not say 100% what caused the error, but clearing the cache fixed it.

**Comment by yanlee26** [comment]
same here
`$ gulp && go run main.go
[14:04:00] Using gulpfile C:\work\src\cedt-icg-bitbucket.nam.nsroot.net\bitbucket\scm\rfq\rfq-web.git\gulpfile.js
[14:04:00] Starting 'build-info'...
[14:04:00] Finished 'build-info' after 1.54 ms
[14:04:00] Starting 'pre-copy-webcomps'...
[14:04:00] Starting 'pre-copy-liberator'...
[14:04:00] Starting 'crisper'...
[14:04:00] Starting 'go-compile'...
[14:04:00] Finished 'go-compile' after 132 ms
[14:04:00] Finished 'pre-copy-liberator' after 335 ms
[14:04:01] Finished 'pre-copy-webcomps' after 453 ms
[14:04:01] Finished 'crisper' after 880 ms
[14:04:01] Starting 'babel'...
[14:04:07] Finished 'babel' after 5.55 s
[14:04:07] Starting 'compile'...
[14:04:08] Finished 'compile' after 1.13 s
[14:04:08] Starting 'copy'...
(node:5808) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: no writecb in Transform class
`
