### ISSUE TITLE
Error with @import

### ISSUE THREAD

**Issue by futurechan** [plus3network/gulp-less#172]
I'm getting an error during gulp-less execution on `@import` statements. If I remove the import, the process completes. This was previously working, but I got a new computer, cloned my projects, ran npm install, and hit this issue.

```
events.js:299
              (list[i].listener && list[i].listener === listener)) {
                      ^
TypeError: Cannot read property 'listener' of undefined
    at DestroyableTransform.removeListener (events.js:299:23)
    at cleanup (C:\Users\joshchan\github.com\compassphs\core-site\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:540:9)
    at DestroyableTransform.onunpipe (C:\Users\joshchan\github.com\compassphs\core-site\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:519:5)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at DestroyableTransform.Readable.unpipe (C:\Users\joshchan\github.com\compassphs\core-site\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:691:12)
    at unpipe (C:\Users\joshchan\github.com\compassphs\core-site\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:584:9)
    at DestroyableTransform.onfinish (C:\Users\joshchan\github.com\compassphs\core-site\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:579:5)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

**Comment by contra** [comment]
Did you change node versions between computers?

**Comment by futurechan** [comment]
Maybe io.js versions...

**Comment by futurechan** [comment]
Indeed. Switching from io.js (latest) to node.js (latest) fixed the issue.

**Comment by futurechan** [comment]
@contra what's the plan to make gulp-less compatible with the latest versions of node?
