### ISSUE TITLE
Undefined Is Not A Function

### ISSUE THREAD

**Issue by examinedliving** [plus3network/gulp-less#180]
This is a new error - thrown without any modification to the code, after changing a few lines that did nothing more than rearrange the white-space.  `lessc --lint` shows nothing.
>
    'less' errored after 5.54 ms
    [23:30:14] TypeError: undefined is not a function
    at Gulp.<anonymous> (	[path to root]\gulpfile.js:85:36)
    at module.exports (	[path to root]\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (	[path to root]\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (	[path to root]\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (	[path to root]\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (	[path to root]\node_modules\gulp\index.js:36:18)
    at Gaze.<anonymous> (	[path to root]\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\index.js:18:14)
    at Gaze.emit (events.js:110:17)
    at Gaze.emit (	[path to root]\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:129:32)
    at 	[path to root]\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:415:16

Every module in my package.json is updated to newest version inculding this one - 3.0.3

**Comment by examinedliving** [comment]
This is actually appears related to a combination of ( (`gulp-autoprefixer` | `less-plugin-autoprefix` ) [issue happens with both] & (`gulp-sourcemaps`) ), as well as possibly `gulp-load-plugins` and certainly `gulp-minify-css`.  I'll leave this open for now, but as I think this is actually related to something other than this plugin, feel free to close it this issue if it is not useful.

**Comment by contra** [comment]
That seems like it's coming from your gulpfile, look at the stack trace
