### ISSUE TITLE
Tests are failing: no writecb in Transform class

### ISSUE THREAD

**Issue by betaorbust** [plus3network/gulp-less#196]
The [tests for gulp-less at the released v3.0.3](https://travis-ci.org/plus3network/gulp-less) are currently failing with:
```
  1) gulp-less less() should compile single less file:
     Uncaught Error: no writecb in Transform class
      at afterTransform (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:33)
      at TransformState.afterTransform (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
      at tryCatchReject (node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
      at Rejected.when (node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
      at Pending.run (node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
```
![image](https://cloud.githubusercontent.com/assets/921683/10352074/d2448ae0-6d01-11e5-9504-be1c8a00274f.png)

![image](https://cloud.githubusercontent.com/assets/921683/10352086/ddfc1d08-6d01-11e5-8be3-6e9cf118f4a5.png)

**Comment by thecotne** [comment]
for me only 2.0.2 worked

```
$ node -v
v0.10.40
$ npm -v
1.4.28
```
