### ISSUE TITLE
Error: less version 1.7.5 is not currently supported

### ISSUE THREAD

**Issue by elranu** [plus3network/gulp-less#208]
I'm getting the following error. Any idea???
```
C:\Dev\Git\btr\Web\node_modules\accord\lib\index.js:31
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 1.7.5 is not currently supported
    at Object.exports.load (C:\Dev\Git\btr\Web\node_modules\accord\lib\index.js:31:13)
    at Object.<anonymous> (C:\Dev\Git\btr\Web\node_modules\gulp-less\index.js:9:29)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Dev\Git\btr\Web\Areas\OffsitePlayer\gulpfile.js:5:12)
    at Module._compile (module.js:398:26)
```

Thanks

**Comment by stevelacy** [comment]
Less 1.x is not supported
