### ISSUE TITLE
less version 1.7.5 is not currently supported

### ISSUE THREAD

**Issue by dangreen** [plus3network/gulp-less#212]
```
error: Gulp :: /Users/dangreen/github/leadbean/node_modules/accord/lib/index.js:31
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 1.7.5 is not currently supported
    at Object.exports.load (/Users/dangreen/github/leadbean/node_modules/accord/lib/index.js:31:13)
    at Object.<anonymous> (/Users/dangreen/github/leadbean/node_modules/gulp-less/index.js:9:29)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/dangreen/github/leadbean/tasks/config/style.js:1:76)
    at Module._compile (module.js:397:26)
```

**Comment by stevelacy** [comment]
#208

**Comment by amyhua** [comment]
`npm install --save less`
