### ISSUE TITLE
Error when processing less

### ISSUE THREAD

**Issue by mojowill** [plus3network/gulp-less#260]
I am getting the following error when trying to compile less using gulp-less.

`Potentially unhandled rejection [2] Error: no writecb in Transform class
    at afterTransform (/Users/mojowill/Sites/london-city-studio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/Users/mojowill/Sites/london-city-studio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /Users/mojowill/Sites/london-city-studio/node_modules/gulp-less/index.js:58:14
    at tryCatchReject (/Users/mojowill/Sites/london-city-studio/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/mojowill/Sites/london-city-studio/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/mojowill/Sites/london-city-studio/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/mojowill/Sites/london-city-studio/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/mojowill/Sites/london-city-studio/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/mojowill/Sites/london-city-studio/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)`

It has previously worked and the only change has been a bump in version number. I even tried explicitly using version 3.1 (which I know was working) and it fails.

`$ npm -v
3.10.9`
`$ node -v
v7.1.0`

My task is 
`gulp.task('less', function() {
	return gulp.src(paths.LESS)
		.pipe(sourcemaps.init())
		.pipe(less())
		.pipe(autoprefixer({
			browser: ['last 2 versions'],
			cascade: false
		}))
		.pipe(cleanCSS())
		.pipe(rename({
			suffix: '.min'
		}))
		.pipe(sourcemaps.write('./'))
		.pipe(gulp.dest(paths.DIST + '/styles'))
		.pipe(browserSync.reload({
			stream: true
		}))
});`

**Comment by mojowill** [comment]
Turned out to be an issue with gulp-autoprefixer needing to use a super old 2.3.1 version
