### ISSUE TITLE
TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by webdesignmx05** [plus3network/gulp-less#264]
Hello,  

I'm experiencing an error when i attempt to run the following gulp task at the command line. 
What could be wrong? I have confirmed in the package.json that "gulp-less": "^3.3.0", is installed as a dependency. I also played around with installed a lower version of gulp-less@3.0.3 and it gave the same error as well.

var gulp = require('gulp'), 
      less = require('gulp-less');

gulp.task('compile-less', function() {
	 return gulp.src('source/less/main.less')
         .pipe(less())
         .pipe(gulp.dest('build/css'));
});

$ gulp compile-less
sass-lang 1.0.0, development build
[10:45:03] Using gulpfile C:\wamp\www\sass-lang\gulpfile.js
[10:45:03] Starting 'compile-less'...
[10:45:03] 'compile-less' errored after 11 ms
[10:45:03] TypeError: less is not a function
    at Gulp.<anonymous> (C:\wamp\www\sass-lang\gulpfile.js:155:12)
    at module.exports (C:\wamp\www\sass-lang\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\wamp\www\sass-lang\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\wamp\www\sass-lang\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\wamp\www\sass-lang\node_modules\orchestrator\index.js:134:8)
    at C:\Users\rramey\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:46:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)

**Comment by stevelacy** [comment]
You did not difine the variable:
```js
var less = require('gulp');
```

**Comment by webdesignmx05** [comment]
No, that was not my code..you deleted my post.

My variables were as follows

var gulp = require('gulp'),
less = require('gulp-less');

Less was defined, task was defined and ran.

**Comment by stevelacy** [comment]
I did NOT delete you post.
Look again at the code you Just posted. Add a `var` before the `less`.

Screenshots for proof so you can not blame me for editing
![selection_00120171110 07 50](https://cloud.githubusercontent.com/assets/5648999/21858316/dc56e8f2-d7e5-11e6-8bf9-3382daa7e775.png)
 Your comment:

![selection_00120171110 04 59](https://cloud.githubusercontent.com/assets/5648999/21858205/7b4484ac-d7e5-11e6-8526-441b5d61c926.png)

Change your less require to this:

![selection_00120171110 07 06](https://cloud.githubusercontent.com/assets/5648999/21858274/b9da3f7c-d7e5-11e6-96eb-1a78dee4ef57.png)
