### ISSUE TITLE
No `sourceMappingURL` appended in the generated css file

### ISSUE THREAD

**Issue by leftstick** [plus3network/gulp-less#88]
I have a simple script

```javascript
var less = require('gulp-less');
    var prefix = require('gulp-autoprefixer');
    var sourcemap = require('gulp-sourcemaps');

    gulp.src(['./less/main.less'])
        .pipe(sourcemap.init())
        .pipe(less({
            compress: false,
            paths: [
                './bower_components/'
            ]
        }))
        .pipe(sourcemap.write('./'))
        .pipe(prefix('last 4 version'))
        .pipe(gulp.dest('./css'));
```

The `sourcemap` is written into a separate file, but no `sourceMappingURL` appended in the generated css file, am i missing something here?

Thanks

**Comment by contra** [comment]
Still an issue after an npm upate and being on the latest less and gulp-less?

**Comment by contra** [comment]
Can you test this on 3.0.0?

**Comment by leftstick** [comment]
The same code, getting errors as following:

    Error: no writecb in Transform class
    at afterTransform (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at tryCatchReject (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/haozuo/codes/github/test/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:442:13)

**Comment by leftstick** [comment]
`3.0.0` works alright, thanks for notifying
